# simple dockerfile to test OCP s2i using Dockerfile 

FROM registry.access.redhat.com/ubi7:latest
#CMD ["/bin/bash", "-c", "sleep infinity"]

#Changes in the Dockerfile to see if the webhook is working and new build is launched in OCP
CMD ["/bin/bash", "-c", "--", "while true; do sleep 30; done;"]
